name: Gerar Gráfico Pac-Man

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gerar gráfico

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerar cards de resumo do perfil
        # Forçando o uso de uma versão antiga que ainda tinha o THEME
        uses: vn7n24fzkq/github-profile-summary-cards@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Gabrielarruda177
          THEME: pacman # Voltamos a adicionar esta linha!
